module.exports = {
  docs: {
    Introduction: [
      'introduction/overview',
      'introduction/wechaty',
      'introduction/motivations',
      'introduction/concepts',
      'introduction/architecture',
      'introduction/lifecycle',
      'examples',
      'examples2',
      'introduction/alternatives',
    ],
    Tutorials: [
      'tutorials/overview',
      'tutorials/video-tutorial',
      'tutorials/docker',
      'tutorials/usage-with-typescript',
      'tutorials/usage-with-heroku',
      'tutorials/using-plugin-with-wechaty',
      'tutorials/using-vorpal-with-wechaty',
      'tutorials/using-redux-with-wechaty',
    ],
    'How-to Guides': [
      'how-tos/overview',
      'how-tos/install',
      'how-tos/wechaty',
      'how-tos/event',
      'how-tos/message',
      'how-tos/contact',
      'how-tos/room',
      'how-tos/friendship',
      'how-tos/file-box',
    ],
    'References': [
      'references/overview',
      {
        type: 'category',
        label: 'API',
        items: [
          'api/overview',
          'api/wechaty',
          'api/message',
          'api/contact',
          'api/room',
          'api/room-invitation',
          'api/friendship',
        ],
      },
      {
        type: 'category',
        label: 'Specifications',
        items: [
          'specs/overview',
          'specs/wechaty',
          'specs/puppet',
          'specs/service',
          'specs/token',
        ],
      }
    ],
    Explainations: [
      'explainations/overview',
    ],
    '-------': [
      'explainations/overview',
    ],
    'Puppet Providers': [
      'puppet-providers/overview',
      'puppet-providers/wechat',
      'puppet-providers/whatsapp',
      'puppet-providers/official-account',
      'puppet-providers/gitter',
      'puppet-providers/lark',
      'puppet-providers/padlocal',
      'puppet-providers/wechat4u',
      'puppet-providers/service',
      'puppet-providers/mock',
      'puppet-providers/diy',
    ],
    'Puppet Services': [
      'puppet-services/overview',
      'puppet-services/wxwork',
      'puppet-services/padlocal',
      'puppet-services/paimon',
      'puppet-services/donut',
      'puppet-services/compatibility',
      'puppet-services/diy',
    ],
    'Polyglot': [
      'polyglot/overview',
      'polyglot/openapi/overview',
      'polyglot/typescript/overview',
      'polyglot/python/overview',
      'polyglot/go/overview',
      'polyglot/java/overview',
      'polyglot/scala/overview',
      'polyglot/php/overview',
      'polyglot/dotnet/overview',
      'polyglot/rust/overview',
      'polyglot/diy/overview',
    ],
    'Getting Started': [
      'getting-started/overview',
      'getting-started/quick-start',
      'getting-started/hard-way',
    ],
    'Case Study': [
      'case-study/overview',
      'case-study/coaxer-bot',
    ],
    'Showcases': [
      'showcases/overview',
      'showcases/osschat-bot',
      'showcases/rui-bot',
      'showcases/friday-bot',
      'showcases/projects-using-wechaty',
    ],
    'Contributing': [
      'contributing/overview',
      'contributing/contributor-program',
      'contributing/publish-blog',
    ],
    'Google Season of Docs': [
      'gsod/overview',
      'gsod/2021',
    ],
    'Events': [
      'events',
      'bot5/overview',
      {
        type: 'category',
        label: '开源软件供应链点亮计划',
        items: [
          'ospp/overview',
          'ospp/2021',
          'ospp/2020',
        ],
      },
      {
        type: 'category',
        label: 'Google Summer of Code',
        items: [
          'gsoc/overview',
          'gsoc/2021',
        ],
      },
    ],
    FAQ: ['faq'],
    Troubleshooting: [
      'troubleshooting',
    ],
    Others: [
      'changelog',
      'cheatsheet',
      'awesome-wechaty',
      'advanced',
      'resources',
      'glossary',
      {
        type: 'category',
        label: 'Docusaurus',
        items: [
          'test/doc1',
          'test/doc2',
          'test/doc3',
          'test/mdx',
        ],
      },
    ],
  },
}
