module.exports = {
  docs: {
    Introduction: [
      'introduction/README',
      'introduction/motivations',
      'introduction/concepts',
      'introduction/architecture',
      'introduction/lifecycle',
      'examples',
      'examples2',
      'introduction/alternatives',
    ],
    'Getting Started': [
      'getting-started/README',
      'getting-started/quick-start',
      'getting-started/hard-way',
    ],
    Tutorials: [
      'tutorials/README',
      'tutorials/video-tutorial',
      'tutorials/docker',
    ],
    'Polyglot': [
      'polyglot/README',
      'polyglot/openapi/README',
      'polyglot/typescript/README',
      'polyglot/python/README',
      'polyglot/go/README',
      'polyglot/java/README',
      'polyglot/scala/README',
      'polyglot/php/README',
      'polyglot/dotnet/README',
      'polyglot/rust/README',
      'polyglot/diy/README',
    ],
    'How-to Guides': [
      'how-tos/README',
      'how-tos/install',
      'how-tos/wechaty',
      'how-tos/event',
      'how-tos/message',
      'how-tos/contact',
      'how-tos/room',
      'how-tos/friendship',
      'how-tos/file-box',
      'how-tos/usage-with-typescript',
      'how-tos/usage-with-heroku',
      'how-tos/using-plugin-with-wechaty',
      'how-tos/using-vorpal-with-wechaty',
      'how-tos/using-redux-with-wechaty',
    ],
    'Case Study': [
      'case-study/README',
      'case-study/coaxer-bot',
    ],
    'Showcases': [
      'showcases/README',
      'showcases/osschat-bot',
      'showcases/rui-bot',
      'showcases/friday-bot',
      'showcases/projects-using-wechaty',
    ],
    'Puppet Providers': [
      'puppet-providers/README',
      'puppet-providers/wechat',
      'puppet-providers/whatsapp',
      'puppet-providers/official-account',
      'puppet-providers/gitter',
      'puppet-providers/lark',
      'puppet-providers/padlocal',
      'puppet-providers/wechat4u',
      'puppet-providers/service',
      'puppet-providers/mock',
      'puppet-providers/diy',
    ],
    'Puppet Services': [
      'puppet-services/README',
      'puppet-services/wxwork',
      'puppet-services/padlocal',
      'puppet-services/paimon',
      'puppet-services/donut',
      'puppet-services/compatibility',
      'puppet-services/diy',
    ],
    'Contributing': [
      'contributing',
      {
        type: 'category',
        label: 'Contributor Program',
        items: [
          'contributor-program/README',
          'contributor-program/publish-blog',
        ],
      },
    ],
    'Google Season of Docs': [
      'gsod/README',
      'gsod/2021',
    ],
    'Events': [
      'events',
      'bot5/README',
      {
        type: 'category',
        label: '开源软件供应链点亮计划',
        items: [
          'ospp/README',
          'ospp/2021',
          'ospp/2020',
        ],
      },
      {
        type: 'category',
        label: 'Google Summer of Code',
        items: [
          'gsoc/README',
          'gsoc/2021',
        ],
      },
    ],
    'References': [
      {
        type: 'category',
        label: 'API',
        items: [
          'api/README',
          'api/wechaty',
          'api/message',
          'api/contact',
          'api/room',
          'api/room-invitation',
          'api/friendship',
        ],
      },
      {
        type: 'category',
        label: 'Specifications',
        items: [
          'specifications/README',
          'specifications/wechaty',
          'specifications/puppet',
          'specifications/service',
          'specifications/token',
        ],
      }
    ],
    FAQ: ['faq'],
    Troubleshooting: [
      'troubleshooting',
    ],
    Others: [
      'changelog',
      'cheatsheet',
      'awesome-wechaty',
      'advanced',
      'resources',
      'glossary',
      'contributing',
      {
        type: 'category',
        label: 'Docusaurus',
        items: [
          'test/doc1',
          'test/doc2',
          'test/doc3',
          'test/mdx',
        ],
      },
    ],
  },
}
