module.exports = {
  docs: {
    Introduction: [
      'README',
      'multi-language',
      'puppet',
      'concepts',
      'motivation',
      'examples',
      'examples2',
      'alternatives',
    ],
    'Getting Started': [
      'getting-started',
    ],
    Tutorials: [
      'tutorials/README',
      'video-tutorial',
    ],
    'API Reference': [
      'api/README',
      'api/wechaty',
      'api/message',
      'api/contact',
      'api/room',
      'api/room-invitation',
      'api/friendship',
    ],
    Recipes: [
      'recipes/README',
      'recipes/configure-wechaty',
      'recipes/usage-with-typescript',
      'recipes/usage-with-docker',
      'recipes/usage-with-heroku',
      'recipes/using-plugin-with-wechaty',
      'recipes/using-vorpal-with-wechaty',
      'recipes/using-redux-with-wechaty',
    ],
    FAQ: [
      'faq/README',
      'faq/general',
      'faq/puppet',
      'faq/miscellaneous',
    ],
    Troubleshooting: [
      'troubleshooting',
    ],
    Others: [
      'release-log',
      'change-log',
      'awesome-wechaty',
      'advanced',
      'tech',
      'glossary',
      'contributing',
      'user-showcases',
    ],
    Docusaurus: [
      'test/doc1',
      'test/doc2',
      'test/doc3',
      'test/mdx',
    ],
  },
}
